version: '3.8'

services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres

  postgres:
    image: postgres:14-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: